# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015, 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

addons:
  postgresql: 9.3

notifications:
  email: false

sudo: false

language: python

cache:
  - pip

services:
  - postgresql
  - redis

env:
  - REQUIREMENTS=lowest SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=devel SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: lnielsen
  password:
    secure: ULExLk0vztTYjTAouexKrdyxs1ZNgY74fhYXiX5g+bGAWuDnFc6EfB3AyGjD8KXG3IkGBKRHEIpIo31IlFl4I/ejXduPN7rSdu4ZXDioiR/d2cBT0fGFlN9zQ2aatEXVa5Axy7DeS3kdr2bhs8Ae/N5XkZtDXrp6wm5imoO2/amysXJeeJ7CVe8cvDd1gM1rX5fxXKjChCoXSyieIE8Ojou/KfuitXFJX4j8xFISybaLPc1JCKqUqco/PJjawERij925EWBkLvTXDi0RBL3UuuS+A6HiO4gXZTOiTKR66suBnjlITvjR0cmVWw23fTtyz0cLY3Myzvb5+UNTuW34ZtFv2HnilA8uE1OB8NZ6Dv6FhFHWspE0uERFESgFJH3wKdeyP4bXV6ZbntEQhnIW9mxpdoCgNn9Ig6xdcHySi6FD2LApfr8ZG9PsZdWrLi1Zk8DI6bemQUkZRMYe9AWf0E+zBTz7a7dca6rF3bo0vDhuJu98eH9/B8cbHCDlMYm812m6Y3IYOYsXIRoA4w3qs9m+eb5DtXGERs2GkrAv4cLgT5HgcOcx8sZ0sbZuuYyxf+hkRN3WKv01rTH3t2WUWEm1StZQRB5qcBH0gts4rk6j7zaF+9kgTIKUVXLot/ZfFOajKC4BD81GfPSh+UZbbJoiKXehixJ+p9aQr35OjAI=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = release
